In [1]:
import numpy as np
import pandas as pd
import datetime as dt
import pandas_datareader.data as web
import bs4 as bs
import urllib.request

start = dt.datetime(2019, 1, 15)
end = dt.datetime.now()

In [56]:
df_old=pd.read_excel('Main_DF.xlsx')
df_old.set_index('Date',inplace=True)
df_old.tail(3)

,MOEXBC,USD_RUB,RGBITR_YIELD,Russia_ETF,OIL,Treas_4M,Copper,Swap_3M,Swap_12M,MOSPRIME_ON,MOSPRIME_3M,EUR_USD,USD_Repo
Date,,,,,,,,,,,,,
2019-06-20,18876.54,62.890,7.35,23.820000,58.180000,2.078,16.990000,0.8240,3.115,7.67,8.04,1.12885,2.27
2019-06-21,18728.82,63.025,7.41,23.660000,58.660999,2.055,16.830000,0.8070,3.105,7.67,8.03,1.13680,2.26
2019-06-24,18719.65,62.600,7.39,23.799999,58.880001,2.058,16.950001,0.8125,3.155,7.66,8.03,1.13960,2.26

In [43]:
SRATE_USD_3M_Date = []
SRATE_USD_3M_Rate = []

source = urllib.request.urlopen('https://www.moex.com/ru/markets/currency/swaps.aspx?code=SRATE_USD_3M').read()
soup = bs.BeautifulSoup(source,'lxml')
table=soup.find('table',{'id':'ctl00_PageContent_ctrlGetSwaps_GridView1'})

for row in table.findAll('tr')[1:]:
    USD_3M_Date = row.findAll('td')[0].text
    SRATE_USD_3M_Date.append(USD_3M_Date)
    USD_3M_Rate= row.findAll('td')[1].text    
    SRATE_USD_3M_Rate.append(USD_3M_Rate)
    
USD_3M = pd.DataFrame({'Date':SRATE_USD_3M_Date,'Swap_3M':SRATE_USD_3M_Rate},columns=['Date', 'Swap_3M'] )
USD_3M['Date']=pd.to_datetime(USD_3M.Date,dayfirst=True)
USD_3M['Swap_3M']= USD_3M.Swap_3M.str.replace(",", ".")
USD_3M['Swap_3M']=USD_3M.Swap_3M.astype(float)
USD_3M.set_index('Date',inplace=True)
USD_3M=USD_3M.head(6)
USD_3M

            Swap_3M
Date
2019-06-25   0.8150
2019-06-24   0.8125
2019-06-21   0.8070
2019-06-20   0.8240
2019-06-19   0.8250
2019-06-18   0.8263

In [44]:
SRATE_USD_1Y_Date = []
SRATE_USD_1Y_Rate = []

source = urllib.request.urlopen('https://www.moex.com/ru/markets/currency/swaps.aspx?code=SRATE_USD_1Y').read()
soup = bs.BeautifulSoup(source,'lxml')
table=soup.find('table',{'id':'ctl00_PageContent_ctrlGetSwaps_GridView1'})

for row in table.findAll('tr')[1:]:
    USD_1Y_Date = row.findAll('td')[0].text
    SRATE_USD_1Y_Date.append(USD_1Y_Date)
    USD_1Y_Rate= row.findAll('td')[1].text    
    SRATE_USD_1Y_Rate.append(USD_1Y_Rate)
    
USD_1Y = pd.DataFrame({'Date':SRATE_USD_1Y_Date,'Swap_12M':SRATE_USD_1Y_Rate},columns=['Date', 'Swap_12M'] )
USD_1Y['Date']=pd.to_datetime(USD_1Y.Date,dayfirst=True)
USD_1Y['Swap_12M']= USD_1Y.Swap_12M.str.replace(",", ".")
USD_1Y['Swap_12M']=USD_1Y.Swap_12M.astype(float)
USD_1Y.set_index('Date',inplace=True)
USD_1Y=USD_1Y.head(6)
USD_1Y

            Swap_12M
Date
2019-06-25     3.175
2019-06-24     3.155
2019-06-21     3.105
2019-06-20     3.115
2019-06-19     3.155
2019-06-18     3.165

In [42]:
MOSPRIME_Date = []
MOSPRIME_ON_Rate = []
MOSPRIME_3M_Rate = []

source = urllib.request.urlopen('http://mosprime.com/archive').read()
soup = bs.BeautifulSoup(source,'lxml')
table=soup.find('table',{'class':'table table-bordered table-condensed arch-table rrr'})

for row in table.findAll('tr')[1:]:
    Date = row.findAll('th')[0].text
    MOSPRIME_Date.append(Date)
    
    MOSPRIME_ON= row.findAll('td')[0].text    
    MOSPRIME_ON_Rate.append(MOSPRIME_ON)
    
    MOSPRIME_3M= row.findAll('td')[5].text    
    MOSPRIME_3M_Rate.append(MOSPRIME_3M)
    
MOS_PRIME = pd.DataFrame({'Date':MOSPRIME_Date,'MOSPRIME_ON':MOSPRIME_ON_Rate,'MOSPRIME_3M':MOSPRIME_3M_Rate},columns=['Date', 'MOSPRIME_ON','MOSPRIME_3M'] )
MOS_PRIME['Date']=pd.to_datetime(MOS_PRIME.Date,dayfirst=True)
MOS_PRIME['MOSPRIME_ON']=MOS_PRIME.MOSPRIME_ON.astype(float)
MOS_PRIME['MOSPRIME_3M']=MOS_PRIME.MOSPRIME_3M.astype(float)
MOS_PRIME.set_index('Date',inplace=True)
MOS_PRIME=MOS_PRIME.head(6)
MOS_PRIME

            MOSPRIME_ON  MOSPRIME_3M
Date
2019-06-25         7.73         8.03
2019-06-24         7.66         8.03
2019-06-21         7.67         8.03
2019-06-20         7.67         8.04
2019-06-19         7.66         8.04
2019-06-18         7.70         8.04
2019-06-17         7.70         8.06

In [45]:
EUR_USD = web.get_data_moex('EURUSD000TOM', '2019-01-15', end)
EUR_USD=EUR_USD.loc[EUR_USD.BOARDID=='CETS']
EUR_USD.drop(['BOARDID', 'SECID', 'SHORTNAME', 'VOLRUR', 'OPEN', 'LOW', 'HIGH', 'NUMTRADES',  'WAPRICE'], 1, inplace=True)
EUR_USD.index.name= 'Date'
EUR_USD.sort_index(inplace=True,ascending=False) 
EUR_USD.rename(columns={'CLOSE':'EUR_USD'}, inplace=True)
EUR_USD=EUR_USD.head(6)
EUR_USD

            EUR_USD
Date
2019-06-25  1.13710
2019-06-24  1.13960
2019-06-21  1.13680
2019-06-20  1.12885
2019-06-19  1.12266
2019-06-18  1.11970

In [46]:
MOEXBC_New= web.get_data_moex('MOEXBC', '2019-05-22', end)
MOEXBC_New.drop(['BOARDID', 'SECID', 'SHORTNAME', 'NAME', 'OPEN', 'LOW', 'HIGH','DECIMALS', 'CURRENCYID',  'DIVISOR','VALUE','DURATION','CAPITALIZATION','YIELD'], 1, inplace=True)
MOEXBC_New.index.name= 'Date'
MOEXBC_New.index=pd.to_datetime(MOEXBC_New.index)
MOEXBC_New.rename(columns={'CLOSE':'MOEXBC'}, inplace=True)
MOEXBC_New.sort_index(inplace=True,ascending=False) 
MOEXBC_New=MOEXBC_New.head(6)
MOEXBC_New

              MOEXBC
Date
2019-06-25  18654.63
2019-06-24  18719.65
2019-06-21  18728.82
2019-06-20  18876.54
2019-06-19  18724.10
2019-06-18  18747.41

In [48]:
USD_RUB_New = web.get_data_moex('USD000UTSTOM', '2019-05-10', end)
USD_RUB_New=USD_RUB_New.loc[USD_RUB_New.BOARDID=='CETS']
USD_RUB_New.drop(['BOARDID', 'SECID', 'SHORTNAME', 'VOLRUR', 'OPEN', 'LOW', 'HIGH', 'NUMTRADES',  'WAPRICE'], 1, inplace=True)
USD_RUB_New.index.name= 'Date'
USD_RUB_New.rename(columns={'CLOSE':'USD_RUB'}, inplace=True)
USD_RUB_New.sort_index(inplace=True,ascending=False) 
USD_RUB_New=USD_RUB_New.head(6)
USD_RUB_New

            USD_RUB
Date
2019-06-25   62.835
2019-06-24   62.600
2019-06-21   63.025
2019-06-20   62.890
2019-06-19   63.785
2019-06-18   64.020

In [49]:
RGBITR_New= web.get_data_moex('RGBITR', '2019-05-22', end)
RGBITR_New.drop(['BOARDID', 'SECID', 'SHORTNAME', 'NAME', 'OPEN', 'LOW', 'HIGH','CLOSE','DECIMALS', 'CURRENCYID',  'DIVISOR','VALUE','DURATION','CAPITALIZATION'], 1, inplace=True)
RGBITR_New.index.name= 'Date'
RGBITR_New.index=pd.to_datetime(RGBITR_New.index)
RGBITR_New.rename(columns={'YIELD':'RGBITR_YIELD'}, inplace=True)
RGBITR_New.sort_index(inplace=True,ascending=False) 
RGBITR_New=RGBITR_New.head(6)
RGBITR_New

            RGBITR_YIELD
Date
2019-06-25          7.38
2019-06-24          7.39
2019-06-21          7.41
2019-06-20          7.35
2019-06-19          7.45
2019-06-18          7.56

In [50]:
USD_Repo = web.get_data_moex('MOEXREPOUSD', start, end)
USD_Repo.drop(['BOARDID', 'SECID', 'SHORTNAME', 'NAME', 'VALUE', 'OPEN', 'LOW', 'HIGH', 'DURATION', 'YIELD', 'DECIMALS', 'CAPITALIZATION', 'CURRENCYID', 'DIVISOR'], 1, inplace=True)
USD_Repo.rename(columns={'CLOSE':'USD_Repo'}, inplace=True)
USD_Repo.index.name= 'Date'
USD_Repo.index=pd.to_datetime(USD_Repo.index)
USD_Repo.sort_index(inplace=True,ascending=False) 
USD_Repo=USD_Repo.head(6)
USD_Repo

            USD_Repo
Date
2019-06-25      2.26
2019-06-24      2.26
2019-06-21      2.26
2019-06-20      2.27
2019-06-19      2.26
2019-06-18      2.25

In [ ]:
my_data=[MOEXBC_New.MOEXBC, USD_RUB_New.USD_RUB,RGBITR_New.RGBITR_YIELD,USD_3M.Swap_3M, USD_1Y.Swap_12M, MOS_PRIME.MOSPRIME_ON, MOS_PRIME.MOSPRIME_3M, ]
my_data=pd.concat(my_data,axis=1)
# my_data.columns = ['Swap_12M','Swap_3M']
my_data.head(5)

In [ ]:
tickers = ['RSX','OIL','^IRX','CPER']
ETFs = pd.DataFrame()    

for ticker in tickers:
        ETF = web.get_data_yahoo(ticker, start, end)
        ETF.rename(columns={'Adj Close': ticker}, inplace=True)
        ETF.drop(['Open', 'High', 'Low', 'Close', 'Volume'], 1, inplace=True)
        if ETFs.empty:
            ETFs = ETF
        else:
            ETFs = ETFs.join(ETF, how='outer')
ETFs.rename(columns={'RSX': 'Russia_ETF', '^IRX':'Treas_4M', 'CPER':'Copper'}, inplace=True)
ETFs.tail(2)

In [18]:
df_old=pd.merge(df_old,Swap_3M,on='Date')

In [23]:
df_old=pd.merge(df_old,Swap_12M,on='Date')
df_old=pd.merge(df_old,MOSPRIME,on='Date')
df_old=pd.merge(df_old,EUR_USD,on='Date')
df_old

,MOEXBC,USD_RUB,RGBITR_YIELD,Russia_ETF,OIL,Treas_4M,Copper,Swap_3M,Swap_12M,MOSPRIME_ON,MOSPRIME_3M,EUR_USD
Date,,,,,,,,,,,,
2019-01-16,16276.52,66.3675,8.20,20.219999,54.209999,2.363,16.740000,0.7914,3.1057,7.85,8.59,1.13900
2019-01-17,16368.09,66.3700,8.23,20.340000,54.240002,2.355,16.879999,0.8025,3.1350,7.86,8.58,1.13850
2019-01-18,16558.31,66.2750,8.22,20.510000,55.509998,2.348,16.980000,0.8035,3.1250,7.87,8.58,1.13625
2019-01-22,16522.48,66.5350,8.24,20.270000,54.650002,2.345,16.620001,0.8208,3.2027,7.98,8.58,1.13610
2019-01-23,16686.16,66.0725,8.24,20.620001,54.192001,2.353,16.660000,0.8155,3.1894,7.98,8.58,1.13805
2019-01-24,16636.58,65.7775,8.21,20.660000,54.807999,2.305,16.559999,0.8015,3.1850,7.95,8.58,1.13080
2019-01-25,16749.85,66.0000,8.22,20.740000,55.169998,2.328,17.070000,0.8125,3.2250,7.95,8.56,1.14120
2019-01-29,16745.97,66.0500,8.27,20.690001,54.939999,2.365,17.010000,0.8073,3.2846,8.01,8.57,1.14332
2019-01-30,16857.04,65.5050,8.23,21.150000,55.950001,2.365,17.370001,0.8006,3.2642,7.98,8.57,1.14805
2019-01-31,16924.60,65.4000,8.10,21.230000,55.590000,2.340,17.370001,0.8287,3.2150,7.96,8.57,1.14405
2019-02-04,16935.20,65.5900,8.12,21.160000,56.389999,2.335,17.540001,0.7917,3.1300,7.78,8.62,1.14375
2019-02-06,17055.53,65.8700,8.09,21.020000,55.650002,2.365,17.680000,0.7900,3.1950,7.83,8.60,1.13655
2019-02-07,16846.59,65.9075,8.13,20.870001,54.250000,2.355,17.719999,0.7873,3.1725,7.81,8.62,1.13449
2019-02-08,16789.98,65.8100,8.14,20.760000,54.299999,2.365,17.580000,0.8035,3.1474,7.80,8.62,1.13240
2019-02-12,17022.70,65.8850,8.17,20.870001,54.768002,2.378,17.360001,0.7725,3.0900,7.77,8.62,1.13350
2019-02-13,16675.75,66.5150,8.20,20.170000,55.681999,2.373,17.350000,0.7675,3.0600,7.75,8.60,1.12660
2019-02-14,16470.58,66.6450,8.36,20.320000,56.202999,2.373,17.360001,0.8225,3.3000,7.74,8.62,1.12960
2019-02-15,16689.57,66.3000,8.27,20.469999,57.493999,2.370,17.590000,0.8125,3.2700,7.82,8.62,1.12965
2019-02-19,16453.03,65.7625,8.28,20.540001,57.919998,2.373,17.969999,0.8075,3.2600,7.82,8.62,1.13420
2019-02-20,16677.15,65.6325,8.29,20.719999,58.548000,2.383,18.230000,0.8025,3.2100,7.84,8.62,1.13430
2019-02-21,16543.40,65.5700,8.27,20.540001,58.209999,2.395,18.170000,0.7825,3.1800,7.69,8.62,1.13342
2019-02-22,16676.19,65.3925,8.26,20.730000,58.650002,2.393,18.440001,0.8115,3.1400,7.58,8.62,1.13300
2019-02-26,16699.10,65.7000,8.25,20.760000,57.040001,2.400,18.430000,0.7925,3.1650,7.71,8.62,1.13915
2019-02-27,16683.33,65.7900,8.27,20.590000,58.425999,2.393,18.549999,0.7835,3.1600,7.78,8.62,1.13700
2019-02-28,16638.24,65.9050,8.26,20.420000,58.633999,2.383,18.410000,0.8375,3.1700,7.82,8.63,1.13756
2019-03-01,16598.35,65.9400,8.25,20.440001,57.195000,2.378,18.260000,0.8100,3.1525,7.86,8.64,1.13635
2019-03-04,16569.79,65.7400,8.24,20.500000,57.980000,2.375,18.219999,0.8136,3.1100,7.88,8.64,1.13350
2019-03-05,16519.20,65.7500,8.26,20.629999,57.939999,2.400,18.370001,0.8090,3.0500,7.88,8.63,1.13074
2019-03-07,16589.53,66.2825,8.27,20.309999,57.987000,2.395,18.240000,0.8318,3.1530,7.92,8.60,1.11821
2019-03-11,16511.38,65.9700,8.26,20.490000,58.220001,2.380,18.190001,0.8325,3.1600,7.89,8.60,1.12420
...,...,...,...,...,...,...,...,...,...,...,...,...
2019-05-06,17412.00,65.2275,8.09,21.400000,64.169998,2.363,17.790001,0.8400,3.1700,7.76,8.25,1.11965
2019-05-07,17286.95,65.4075,8.08,21.160000,62.560001,2.368,17.430000,0.8388,3.1600,7.76,8.25,1.11908
2019-05-08,17158.31,65.0725,8.07,21.160000,63.270000,2.370,17.340000,0.8350,3.1600,7.77,8.27,1.11990
2019-05-13,16936.19,65.4300,8.09,20.660000,62.178001,2.350,16.990000,0.8400,3.1800,7.78,8.23,1.12260
2019-05-14,17361.79,64.9700,8.08,21.139999,63.134998,2.353,17.010000,0.8600,3.2300,7.85,8.23,1.12000
2019-05-15,17305.71,64.6500,8.06,21.170000,63.709999,2.350,17.160000,0.8480,3.2400,7.83,8.23,1.11996
2019-05-17,17500.70,64.7775,7.97,21.139999,64.178001,2.330,17.080000,0.8450,3.1700,7.80,8.23,1.11550
2019-05-20,17445.12,64.5250,7.93,21.209999,64.559998,2.320,17.059999,0.8400,3.1600,7.79,8.23,1.11648
2019-05-21,17800.56,64.4100,7.91,21.559999,64.419998,2.330,17.000000,0.8463,3.1800,7.84,8.24,1.11605
2019-05-23,17815.26,64.8550,7.85,21.400000,59.316002,2.303,16.790001,0.8565,3.1250,7.71,8.21,1.11760
2019-05-24,17781.16,64.4725,7.85,21.620001,60.090000,2.288,16.910000,0.8450,3.1400,7.63,8.20,1.12046
2019-05-28,17693.94,64.7150,7.85,21.389999,60.040001,2.298,16.840000,0.8400,3.1300,7.88,8.18,1.11619
2019-05-29,17938.14,64.9700,7.88,21.740000,60.122002,2.298,16.670000,0.8450,3.1700,7.92,8.19,1.11326
2019-05-30,18087.47,65.1700,7.84,21.700001,57.709999,2.310,16.559999,0.8390,3.1600,8.08,8.22,1.11284
2019-05-31,18134.33,65.4300,7.83,21.639999,54.382000,2.293,16.469999,0.8500,3.2400,8.09,8.23,1.11666
2019-06-03,18644.95,65.3400,7.85,22.080000,53.965000,2.280,16.620001,0.8600,3.3400,7.99,8.23,1.12418
2019-06-04,18445.02,65.1650,7.82,22.049999,54.689999,2.295,16.670000,0.8600,3.2700,7.96,8.24,1.12530
2019-06-05,18408.07,65.3950,7.75,22.000000,52.849998,2.285,16.410000,0.8350,3.2375,7.88,8.24,1.12200
2019-06-06,18585.21,65.0850,7.70,22.230000,54.334000,2.255,16.530001,0.8650,3.2649,7.91,8.24,1.12676
2019-06-07,18588.37,64.8050,7.67,22.320000,55.189999,2.215,16.370001,0.8375,3.1900,7.93,8.24,1.13345
2019-06-10,18686.22,64.7800,7.64,22.459999,54.472000,2.220,16.650000,0.8325,3.1700,7.94,8.21,1.13168
2019-06-11,18726.01,64.5575,7.62,22.790001,54.491001,2.213,16.719999,0.8275,3.1450,7.86,8.18,1.13290
2019-06-13,18752.39,64.5800,7.64,22.860001,53.342999,2.140,16.610001,0.8425,3.1350,7.82,8.18,1.12714
2019-06-14,18594.47,64.3800,7.61,22.790001,53.750000,2.125,16.430000,0.8175,3.1850,7.81,8.14,1.12055
2019-06-17,18540.65,64.3200,7.57,22.900000,53.088001,2.138,16.570000,0.8200,3.1650,7.70,8.06,1.12160
2019-06-18,18747.41,64.0200,7.56,23.250000,55.247002,2.168,16.930000,0.8263,3.1650,7.70,8.04,1.11970
2019-06-19,18724.10,63.7850,7.45,23.280001,55.573002,2.125,16.820000,0.8250,3.1550,7.66,8.04,1.12266
2019-06-20,18876.54,62.8900,7.35,23.820000,58.180000,2.078,16.990000,0.8240,3.1150,7.67,8.04,1.12885
2019-06-21,18728.82,63.0250,7.41,23.660000,58.660999,2.055,16.830000,0.8070,3.1050,7.67,8.03,1.13680
2019-06-24,18719.65,62.6000,7.39,23.799999,58.880001,2.058,16.950001,0.8125,3.1550,7.66,8.03,1.13960

In [24]:
df_old.to_excel("Main_DF.xlsx")

In [24]:
df_New=pd.merge(MOEXBC_New,USD_RUB_New,on='Date')
df_New.tail(2)

              MOEXBC  USD_RUB
Date
2019-06-21  18728.82   63.025
2019-06-24  18719.65   62.600

In [26]:
df_New=pd.merge(df_New,RGBITR_New,on='Date')
df_New.tail(2)

              MOEXBC  USD_RUB  RGBITR_YIELD
Date
2019-06-21  18728.82   63.025          7.41
2019-06-24  18719.65   62.600          7.39

In [28]:
df_New=pd.merge(df_New,ETFs,on='Date')
df_New.tail(2)

,MOEXBC,USD_RUB,RGBITR_YIELD,Russia_ETF,OIL,Treas_4M,Copper
Date,,,,,,,
2019-06-21,18728.82,63.025,7.41,23.660000,58.660999,2.055,16.830000
2019-06-24,18719.65,62.600,7.39,23.799999,58.880001,2.058,16.950001

In [29]:
df = df_old.append(df_New)
df.index=pd.to_datetime(df.index)
df.sort_index(inplace=True)
df.drop_duplicates(subset='MOEXBC',inplace=True)
df.tail(3)

,MOEXBC,USD_RUB,RGBITR_YIELD,Russia_ETF,OIL,Treas_4M,Copper
Date,,,,,,,
2019-06-20,18876.54,62.890,7.35,23.820000,58.180000,2.078,16.990000
2019-06-21,18728.82,63.025,7.41,23.660000,58.660999,2.055,16.830000
2019-06-24,18719.65,62.600,7.39,23.799999,58.880001,2.058,16.950001

In [30]:
df.to_excel("Main_DF.xlsx")

In [32]:
df=pd.merge(df,Swap_ON,on='Date')
df.tail(3)

,MOEXBC,USD_RUB,RGBITR_YIELD,Russia_ETF,OIL,Treas_4M,Copper,Swap_ON
Date,,,,,,,,
2019-06-13,18752.39,64.58,7.64,22.860001,53.342999,2.140,16.610001,5.20
2019-06-14,18594.47,64.38,7.61,22.790001,53.750000,2.125,16.430000,5.30
2019-06-17,18540.65,64.32,7.57,22.900000,53.088001,2.138,16.570000,5.22

            USD_Repo
Date
2019-06-20      2.27
2019-06-21      2.26
2019-06-24      2.26

In [34]:
df=pd.merge(df,USD_Repo,on='Date')
df
df['Swap_ON_10']=df.Swap_ON*10

In [36]:

df.head(3)

,MOEXBC,USD_RUB,RGBITR_YIELD,Russia_ETF,OIL,Treas_4M,Copper,Swap_ON,USD_Repo,Swap_ON_10
Date,,,,,,,,,,
2019-01-29,16745.97,66.050,8.27,20.690001,54.939999,2.365,17.010000,5.41,2.51,54.1
2019-01-30,16857.04,65.505,8.23,21.150000,55.950001,2.365,17.370001,5.19,2.50,51.9
2019-01-31,16924.60,65.400,8.10,21.230000,55.590000,2.340,17.370001,5.25,2.52,52.5

In [ ]:
my_data=[USD_3M.Swap_3M, USD_1Y.Swap_12M]
my_data=pd.concat(my_data,axis=1)
# my_data.columns = ['Swap_12M','Swap_3M']
my_data.head(5)

In [18]:
df.corr()

,MOEXBC,USD_RUB,RGBITR_YIELD,Russia_ETF,OIL,Treas_4M,Copper,Swap_ON,USD_Repo,Swap_ON_10
MOEXBC,1.000000,-0.374932,-0.920760,0.899919,-0.213197,-0.853079,-0.740220,0.302286,-0.595150,0.302286
USD_RUB,-0.374932,1.000000,0.369784,-0.656250,-0.530891,0.159580,-0.045022,-0.143120,0.507130,-0.143120
RGBITR_YIELD,-0.920760,0.369784,1.000000,-0.832125,0.364496,0.883093,0.813975,-0.233984,0.583764,-0.233984
Russia_ETF,0.899919,-0.656250,-0.832125,1.000000,-0.044088,-0.754527,-0.508495,0.171579,-0.608514,0.171579
OIL,-0.213197,-0.530891,0.364496,-0.044088,1.000000,0.457961,0.544260,0.152157,-0.060553,0.152157
Treas_4M,-0.853079,0.159580,0.883093,-0.754527,0.457961,1.000000,0.765342,-0.132619,0.464914,-0.132619
Copper,-0.740220,-0.045022,0.813975,-0.508495,0.544260,0.765342,1.000000,-0.222589,0.232837,-0.222589
Swap_ON,0.302286,-0.143120,-0.233984,0.171579,0.152157,-0.132619,-0.222589,1.000000,-0.375495,1.000000
USD_Repo,-0.595150,0.507130,0.583764,-0.608514,-0.060553,0.464914,0.232837,-0.375495,1.000000,-0.375495
Swap_ON_10,0.302286,-0.143120,-0.233984,0.171579,0.152157,-0.132619,-0.222589,1.000000,-0.375495,1.000000

In [37]:
df_prst=df.pct_change()
df_prst.dropna(inplace=True)
df_prst.head(3)

,MOEXBC,USD_RUB,RGBITR_YIELD,Russia_ETF,OIL,Treas_4M,Copper,Swap_ON,USD_Repo,Swap_ON_10
Date,,,,,,,,,,
2019-01-30,0.006633,-0.008251,-0.004837,0.022233,0.018384,0.000000,0.021164,-0.040665,-0.003984,-0.040665
2019-01-31,0.004008,-0.001603,-0.015796,0.003783,-0.006434,-0.010571,0.000000,0.011561,0.008000,0.011561
2019-02-04,0.000626,0.002905,0.002469,-0.003297,0.014391,-0.002137,0.009787,-0.024762,0.007937,-0.024762

In [38]:
df_prst.corr()

,MOEXBC,USD_RUB,RGBITR_YIELD,Russia_ETF,OIL,Treas_4M,Copper,Swap_ON,USD_Repo,Swap_ON_10
MOEXBC,1.000000,-0.248010,-0.205030,0.633449,0.152360,0.103504,0.196259,0.017506,-0.206071,0.017506
USD_RUB,-0.248010,1.000000,0.211125,-0.761419,-0.475700,-0.097967,-0.373386,-0.003497,0.145068,-0.003497
RGBITR_YIELD,-0.205030,0.211125,1.000000,-0.143436,0.104556,0.036740,-0.064816,-0.059469,0.034751,-0.059469
Russia_ETF,0.633449,-0.761419,-0.143436,1.000000,0.354963,0.113583,0.335346,-0.025055,-0.172952,-0.025055
OIL,0.152360,-0.475700,0.104556,0.354963,1.000000,0.164858,0.315009,0.110449,0.057528,0.110449
Treas_4M,0.103504,-0.097967,0.036740,0.113583,0.164858,1.000000,0.133172,-0.029328,-0.269983,-0.029328
Copper,0.196259,-0.373386,-0.064816,0.335346,0.315009,0.133172,1.000000,-0.074325,-0.075474,-0.074325
Swap_ON,0.017506,-0.003497,-0.059469,-0.025055,0.110449,-0.029328,-0.074325,1.000000,0.074131,1.000000
USD_Repo,-0.206071,0.145068,0.034751,-0.172952,0.057528,-0.269983,-0.075474,0.074131,1.000000,0.074131
Swap_ON_10,0.017506,-0.003497,-0.059469,-0.025055,0.110449,-0.029328,-0.074325,1.000000,0.074131,1.000000

In [44]:
corr_data=df
corr_data.dropna(inplace=True)
corr_data.head(3)

Empty DataFrame
Columns: [MOEXBC, USD_RUB, RGBITR_YIELD, Russia_ETF, OIL, Treas_4M, Copper, Swap_ON, USD_Repo, Swap_ON_10]
Index: []

In [42]:

corr_data.MOEXBC=((df.MOEXBC-df.MOEXBC[0])/df.MOEXBC[0]).round(4)*100
corr_data.USD_RUB=((df.USD_RUB-df.USD_RUB[0])/df.USD_RUB[0]).round(4)*100
corr_data.RGBITR_YIELD=((df.RGBITR_YIELD-df.RGBITR_YIELD[0])/df.RGBITR_YIELD[0]).round(4)*100
corr_data.Russia_ETF=((df.Russia_ETF-df.Russia_ETF[0])/df.Russia_ETF[0]).round(4)*100
corr_data.OIL=((df.OIL-df.OIL[0])/df.OIL[0]).round(4)*100
corr_data.Treas_4M=((df.Treas_4M-df.Treas_4M[0])/df.Treas_4M[0]).round(4)*100
corr_data.Copper=((df.Copper-df.Copper[0])/df.Copper[0]).round(4)*100
corr_data.Swap_ON=((df.Swap_ON-df.Swap_ON[0])/df.Swap_ON[0]).round(4)*100
corr_data.USD_Repo=((df.USD_Repo-df.USD_Repo[0])/df.USD_Repo[0]).round(4)*100
corr_data.Swap_ON_10=((df.Swap_ON_10-df.Swap_ON_10[0])/df.Swap_ON_10[0]).round(4)*100

In [34]:
df=df.loc[df.index>=dt.datetime(2019, 1, 15)]
df

,MOEXBC,USD_RUB,RGBITR_YIELD,Russia_ETF,OIL,Treas_4M,Copper,Swap_ON,USD_Repo
Date,,,,,,,,,
2019-01-29,16745.97,66.0500,8.27,20.690001,54.939999,2.365,17.010000,5.41,2.51
2019-01-30,16857.04,65.5050,8.23,21.150000,55.950001,2.365,17.370001,5.19,2.50
2019-01-31,16924.60,65.4000,8.10,21.230000,55.590000,2.340,17.370001,5.25,2.52
2019-02-04,16935.20,65.5900,8.12,21.160000,56.389999,2.335,17.540001,5.12,2.54
2019-02-06,17055.53,65.8700,8.09,21.020000,55.650002,2.365,17.680000,5.17,2.45
2019-02-07,16846.59,65.9075,8.13,20.870001,54.250000,2.355,17.719999,5.10,2.41
2019-02-08,16789.98,65.8100,8.14,20.760000,54.299999,2.365,17.580000,5.32,2.43
2019-02-12,17022.70,65.8850,8.17,20.870001,54.768002,2.378,17.360001,5.21,2.42
2019-02-13,16675.75,66.5150,8.20,20.170000,55.681999,2.373,17.350000,5.11,2.43
2019-02-14,16470.58,66.6450,8.36,20.320000,56.202999,2.373,17.360001,5.11,2.41
2019-02-15,16689.57,66.3000,8.27,20.469999,57.493999,2.370,17.590000,5.32,2.41
2019-02-19,16453.03,65.7625,8.28,20.540001,57.919998,2.373,17.969999,5.40,2.42
2019-02-20,16677.15,65.6325,8.29,20.719999,58.548000,2.383,18.230000,5.36,2.42
2019-02-21,16543.40,65.5700,8.27,20.540001,58.209999,2.395,18.170000,5.01,2.41
2019-02-22,16676.19,65.3925,8.26,20.730000,58.650002,2.393,18.440001,5.17,2.41
2019-02-26,16699.10,65.7000,8.25,20.760000,57.040001,2.400,18.430000,5.30,2.40
2019-02-27,16683.33,65.7900,8.27,20.590000,58.425999,2.393,18.549999,5.32,2.39
2019-02-28,16638.24,65.9050,8.26,20.420000,58.633999,2.383,18.410000,5.32,2.44
2019-03-01,16598.35,65.9400,8.25,20.440001,57.195000,2.378,18.260000,5.39,2.39
2019-03-04,16569.79,65.7400,8.24,20.500000,57.980000,2.375,18.219999,5.33,2.37
2019-03-05,16519.20,65.7500,8.26,20.629999,57.939999,2.400,18.370001,5.33,2.37
2019-03-07,16589.53,66.2825,8.27,20.309999,57.987000,2.395,18.240000,5.53,2.36
2019-03-11,16511.38,65.9700,8.26,20.490000,58.220001,2.380,18.190001,5.41,2.37
2019-03-12,16524.74,65.6350,8.25,20.559999,58.328999,2.395,18.340000,5.36,2.37
2019-03-15,16573.77,64.8150,8.24,20.870001,59.849998,2.388,18.209999,5.33,2.33
2019-03-18,16622.23,64.3650,8.17,21.299999,60.419998,2.385,18.230000,5.27,2.33
2019-03-19,16701.09,64.3900,8.13,21.230000,60.273998,2.405,18.270000,5.32,2.34
2019-03-20,16795.27,63.8675,8.16,21.410000,61.299000,2.408,18.350000,5.16,2.35
2019-03-21,16820.87,63.8700,8.06,21.469999,61.016998,2.408,18.209999,5.22,2.35
2019-03-22,16704.60,64.6600,8.10,20.900000,60.075001,2.398,17.840000,5.11,2.35
...,...,...,...,...,...,...,...,...,...
2019-04-24,17428.23,64.3225,8.17,21.610001,67.139999,2.375,18.270000,5.15,2.37
2019-04-25,17279.97,64.6550,8.19,21.490000,66.369003,2.365,17.920000,5.56,2.39
2019-04-26,17286.76,64.7350,8.17,21.420000,64.269997,2.360,18.110001,5.26,2.36
2019-04-29,17345.68,64.4575,8.12,21.540001,64.940002,2.360,18.139999,5.30,2.37
2019-04-30,17266.96,64.6225,8.07,21.540001,65.266998,2.368,18.180000,5.59,2.39
2019-05-06,17412.00,65.2275,8.09,21.400000,64.169998,2.363,17.790001,4.88,2.41
2019-05-07,17286.95,65.4075,8.08,21.160000,62.560001,2.368,17.430000,5.20,2.41
2019-05-08,17158.31,65.0725,8.07,21.160000,63.270000,2.370,17.340000,5.29,2.40
2019-05-13,16936.19,65.4300,8.09,20.660000,62.178001,2.350,16.990000,5.48,2.38
2019-05-14,17361.79,64.9700,8.08,21.139999,63.134998,2.353,17.010000,5.69,2.36
2019-05-15,17305.71,64.6500,8.06,21.170000,63.709999,2.350,17.160000,5.50,2.38
2019-05-17,17500.70,64.7775,7.97,21.139999,64.178001,2.330,17.080000,5.57,2.36
2019-05-20,17445.12,64.5250,7.93,21.209999,64.559998,2.320,17.059999,5.70,2.36
2019-05-21,17800.56,64.4100,7.91,21.559999,64.419998,2.330,17.000000,5.72,2.34
2019-05-23,17815.26,64.8550,7.85,21.400000,59.316002,2.303,16.790001,5.22,2.33
2019-05-24,17781.16,64.4725,7.85,21.620001,60.090000,2.288,16.910000,5.32,2.33
2019-05-28,17693.94,64.7150,7.85,21.389999,60.040001,2.298,16.840000,5.78,2.34
2019-05-29,17938.14,64.9700,7.88,21.740000,60.122002,2.298,16.670000,5.76,2.34
2019-05-30,18087.47,65.1700,7.84,21.700001,57.709999,2.310,16.559999,6.05,2.31
2019-05-31,18134.33,65.4300,7.83,21.639999,54.382000,2.293,16.469999,5.85,2.31
2019-06-03,18644.95,65.3400,7.85,22.080000,53.965000,2.280,16.620001,6.05,2.29
2019-06-04,18445.02,65.1650,7.82,22.049999,54.689999,2.295,16.670000,5.42,2.31
2019-06-05,18408.07,65.3950,7.75,22.000000,52.849998,2.285,16.410000,5.54,2.31
2019-06-06,18585.21,65.0850,7.70,22.230000,54.334000,2.255,16.530001,5.42,2.30
2019-06-07,18588.37,64.8050,7.67,22.320000,55.189999,2.215,16.370001,5.53,2.30
2019-06-10,18686.22,64.7800,7.64,22.459999,54.472000,2.220,16.650000,5.40,2.31
2019-06-11,18726.01,64.5575,7.62,22.790001,54.491001,2.213,16.719999,5.19,2.26
2019-06-13,18752.39,64.5800,7.64,22.860001,53.342999,2.140,16.610001,5.20,2.26
2019-06-14,18594.47,64.3800,7.61,22.790001,53.750000,2.125,16.430000,5.30,2.26
2019-06-17,18540.65,64.3200,7.57,22.900000,53.088001,2.138,16.570000,5.22,2.25

In [35]:
df.corr()

,MOEXBC,USD_RUB,RGBITR_YIELD,Russia_ETF,OIL,Treas_4M,Copper,Swap_ON,USD_Repo
MOEXBC,1.000000,-0.374932,-0.920760,0.899919,-0.213197,-0.853079,-0.740220,0.302286,-0.595150
USD_RUB,-0.374932,1.000000,0.369784,-0.656250,-0.530891,0.159580,-0.045022,-0.143120,0.507130
RGBITR_YIELD,-0.920760,0.369784,1.000000,-0.832125,0.364496,0.883093,0.813975,-0.233984,0.583764
Russia_ETF,0.899919,-0.656250,-0.832125,1.000000,-0.044088,-0.754527,-0.508495,0.171579,-0.608514
OIL,-0.213197,-0.530891,0.364496,-0.044088,1.000000,0.457961,0.544260,0.152157,-0.060553
Treas_4M,-0.853079,0.159580,0.883093,-0.754527,0.457961,1.000000,0.765342,-0.132619,0.464914
Copper,-0.740220,-0.045022,0.813975,-0.508495,0.544260,0.765342,1.000000,-0.222589,0.232837
Swap_ON,0.302286,-0.143120,-0.233984,0.171579,0.152157,-0.132619,-0.222589,1.000000,-0.375495
USD_Repo,-0.595150,0.507130,0.583764,-0.608514,-0.060553,0.464914,0.232837,-0.375495,1.000000

In [36]:
df=df.pct_change()
df

,MOEXBC,USD_RUB,RGBITR_YIELD,Russia_ETF,OIL,Treas_4M,Copper,Swap_ON,USD_Repo
Date,,,,,,,,,
2019-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-30,0.006633,-0.008251,-0.004837,0.022233,0.018384,0.000000e+00,0.021164,-0.040665,-0.003984
2019-01-31,0.004008,-0.001603,-0.015796,0.003783,-0.006434,-1.057086e-02,0.000000,0.011561,0.008000
2019-02-04,0.000626,0.002905,0.002469,-0.003297,0.014391,-2.136699e-03,0.009787,-0.024762,0.007937
2019-02-06,0.007105,0.004269,-0.003695,-0.006616,-0.013123,1.284795e-02,0.007982,0.009766,-0.035433
2019-02-07,-0.012251,0.000569,0.004944,-0.007136,-0.025157,-4.228326e-03,0.002262,-0.013540,-0.016327
2019-02-08,-0.003360,-0.001479,0.001230,-0.005271,0.000922,4.246280e-03,-0.007901,0.043137,0.008299
2019-02-12,0.013861,0.001140,0.003686,0.005299,0.008619,5.496834e-03,-0.012514,-0.020677,-0.004115
2019-02-13,-0.020382,0.009562,0.003672,-0.033541,0.016689,-2.102655e-03,-0.000576,-0.019194,0.004132
2019-02-14,-0.012303,0.001954,0.019512,0.007437,0.009357,0.000000e+00,0.000576,0.000000,-0.008230
2019-02-15,0.013296,-0.005177,-0.010766,0.007382,0.022970,-1.264231e-03,0.013249,0.041096,0.000000
2019-02-19,-0.014173,-0.008107,0.001209,0.003420,0.007409,1.265832e-03,0.021603,0.015038,0.004149
2019-02-20,0.013622,-0.001977,0.001208,0.008763,0.010843,4.214071e-03,0.014469,-0.007407,0.000000
2019-02-21,-0.008020,-0.000952,-0.002413,-0.008687,-0.005773,5.035705e-03,-0.003291,-0.065299,-0.004132
2019-02-22,0.008027,-0.002707,-0.001209,0.009250,0.007559,-8.351121e-04,0.014860,0.031936,0.000000
2019-02-26,0.001374,0.004702,-0.001211,0.001447,-0.027451,2.925286e-03,-0.000542,0.025145,-0.004149
2019-02-27,-0.000944,0.001370,0.002424,-0.008189,0.024299,-2.916753e-03,0.006511,0.003774,-0.004167
2019-02-28,-0.002703,0.001748,-0.001209,-0.008256,0.003560,-4.178851e-03,-0.007547,0.000000,0.020921
2019-03-01,-0.002397,0.000531,-0.001211,0.000979,-0.024542,-2.098144e-03,-0.008148,0.013158,-0.020492
2019-03-04,-0.001721,-0.003033,-0.001212,0.002935,0.013725,-1.261573e-03,-0.002191,-0.011132,-0.008368
2019-03-05,-0.003053,0.000152,0.002427,0.006341,-0.000690,1.052636e-02,0.008233,0.000000,0.000000
2019-03-07,0.004257,0.008099,0.001211,-0.015511,0.000811,-2.083381e-03,-0.007077,0.037523,-0.004219
2019-03-11,-0.004711,-0.004715,-0.001209,0.008863,0.004018,-6.262992e-03,-0.002741,-0.021700,0.004237
2019-03-12,0.000809,-0.005078,-0.001211,0.003416,0.001872,6.302465e-03,0.008246,-0.009242,0.000000
2019-03-15,0.002967,-0.012493,-0.001212,0.015078,0.026076,-2.922743e-03,-0.007088,-0.005597,-0.016878
2019-03-18,0.002924,-0.006943,-0.008495,0.020604,0.009524,-1.256290e-03,0.001098,-0.011257,0.000000
2019-03-19,0.004744,0.000388,-0.004896,-0.003286,-0.002416,8.385736e-03,0.002194,0.009488,0.004292
2019-03-20,0.005639,-0.008115,0.003690,0.008479,0.017006,1.247410e-03,0.004379,-0.030075,0.004274
2019-03-21,0.001524,0.000039,-0.012255,0.002802,-0.004600,0.000000e+00,-0.007629,0.011628,0.000000
2019-03-22,-0.006912,0.012369,0.004963,-0.026549,-0.015438,-4.152820e-03,-0.020318,-0.021073,0.000000
...,...,...,...,...,...,...,...,...,...
2019-04-24,-0.003409,0.009971,0.000000,-0.016386,-0.008638,-6.276194e-03,0.006057,-0.020913,0.000000
2019-04-25,-0.008507,0.005169,0.002448,-0.005553,-0.011483,-4.210522e-03,-0.019157,0.079612,0.008439
2019-04-26,0.000393,0.001237,-0.002442,-0.003257,-0.031626,-2.114213e-03,0.010603,-0.053957,-0.012552
2019-04-29,0.003408,-0.004287,-0.006120,0.005602,0.010425,0.000000e+00,0.001656,0.007605,0.004237
2019-04-30,-0.004538,0.002560,-0.006158,0.000000,0.005035,3.389888e-03,0.002205,0.054717,0.008439
2019-05-06,0.008400,0.009362,0.002478,-0.006500,-0.016808,-2.111535e-03,-0.021452,-0.127013,0.008368
2019-05-07,-0.007182,0.002760,-0.001236,-0.011215,-0.025090,2.116003e-03,-0.020236,0.065574,0.000000
2019-05-08,-0.007441,-0.005122,-0.001238,0.000000,0.011349,8.445334e-04,-0.005164,0.017308,-0.004149
2019-05-13,-0.012945,0.005494,0.002478,-0.023629,-0.017259,-8.438811e-03,-0.020185,0.035917,-0.008333
2019-05-14,0.025130,-0.007030,-0.001236,0.023233,0.015391,1.276605e-03,0.001177,0.038321,-0.008403
2019-05-15,-0.003230,-0.004925,-0.002475,0.001419,0.009107,-1.274977e-03,0.008818,-0.033392,0.008475
2019-05-17,0.011267,0.001972,-0.011166,-0.001417,0.007346,-8.510631e-03,-0.004662,0.012727,-0.008403
2019-05-20,-0.003176,-0.003898,-0.005019,0.003311,0.005952,-4.291842e-03,-0.001171,0.023339,0.000000
2019-05-21,0.020375,-0.001782,-0.002522,0.016502,-0.002169,4.310341e-03,-0.003517,0.003509,-0.008475
2019-05-23,0.000826,0.006909,-0.007585,-0.007421,-0.079230,-1.158796e-02,-0.012353,-0.087413,-0.004274
2019-05-24,-0.001914,-0.005898,0.000000,0.010280,0.013049,-6.513186e-03,0.007147,0.019157,0.000000
2019-05-28,-0.004905,0.003761,0.000000,-0.010638,-0.000832,4.370625e-03,-0.004140,0.086466,0.004292
2019-05-29,0.013801,0.003940,0.003822,0.016363,0.001366,-2.220446e-16,-0.010095,-0.003460,0.000000
2019-05-30,0.008325,0.003078,-0.005076,-0.001840,-0.040118,5.221865e-03,-0.006599,0.050347,-0.012821
2019-05-31,0.002591,0.003990,-0.001276,-0.002765,-0.057668,-7.359290e-03,-0.005435,-0.033058,0.000000
2019-06-03,0.028158,-0.001376,0.002554,0.020333,-0.007668,-5.669434e-03,0.009108,0.034188,-0.008658
2019-06-04,-0.010723,-0.002678,-0.003822,-0.001359,0.013435,6.578993e-03,0.003008,-0.104132,0.008734
2019-06-05,-0.002003,0.003530,-0.008951,-0.002268,-0.033644,-4.357294e-03,-0.015597,0.022140,0.000000
2019-06-06,0.009623,-0.004740,-0.006452,0.010455,0.028079,-1.312909e-02,0.007313,-0.021661,-0.004329
2019-06-07,0.000170,-0.004302,-0.003896,0.004049,0.015754,-1.773845e-02,-0.009679,0.020295,0.000000
2019-06-10,0.005264,-0.000386,-0.003911,0.006272,-0.013010,2.257388e-03,0.017104,-0.023508,0.004348
2019-06-11,0.002129,-0.003435,-0.002618,0.014693,0.000349,-3.153139e-03,0.004204,-0.038889,-0.021645
2019-06-13,0.001409,0.000349,0.002625,0.003072,-0.021068,-3.298687e-02,-0.006579,0.001927,0.000000
2019-06-14,-0.008421,-0.003097,-0.003927,-0.003062,0.007630,-7.009394e-03,-0.010837,0.019231,0.000000
2019-06-17,-0.002894,-0.000932,-0.005256,0.004827,-0.012316,6.117652e-03,0.008521,-0.015094,-0.004425

In [37]:
df.dropna(inplace=True)
df.corr()

,MOEXBC,USD_RUB,RGBITR_YIELD,Russia_ETF,OIL,Treas_4M,Copper,Swap_ON,USD_Repo
MOEXBC,1.000000,-0.248010,-0.205030,0.633449,0.152360,0.103504,0.196259,0.017506,-0.206071
USD_RUB,-0.248010,1.000000,0.211125,-0.761419,-0.475700,-0.097967,-0.373386,-0.003497,0.145068
RGBITR_YIELD,-0.205030,0.211125,1.000000,-0.143436,0.104556,0.036740,-0.064816,-0.059469,0.034751
Russia_ETF,0.633449,-0.761419,-0.143436,1.000000,0.354963,0.113583,0.335346,-0.025055,-0.172952
OIL,0.152360,-0.475700,0.104556,0.354963,1.000000,0.164858,0.315009,0.110449,0.057528
Treas_4M,0.103504,-0.097967,0.036740,0.113583,0.164858,1.000000,0.133172,-0.029328,-0.269983
Copper,0.196259,-0.373386,-0.064816,0.335346,0.315009,0.133172,1.000000,-0.074325,-0.075474
Swap_ON,0.017506,-0.003497,-0.059469,-0.025055,0.110449,-0.029328,-0.074325,1.000000,0.074131
USD_Repo,-0.206071,0.145068,0.034751,-0.172952,0.057528,-0.269983,-0.075474,0.074131,1.000000

In [46]:
df.isnull().sum()

Swap_3M        0
MOSPRIME_ON    0
MOSPRIME_3M    0
USD_RUB        0
dtype: int64

In [52]:
# df=pd.merge(df,Brent,on='Date')
# df.tail(2)

In [53]:
# LIBOR_USD=pd.read_csv('LIBOR_USD.csv')
# LIBOR_USD.rename(columns={'3M': 'LIBOR_3M' },inplace=True)
# LIBOR_USD.drop(['Week day','ON','1W','1M','2M','6M','12M'],1,inplace=True)
# LIBOR_USD['Date']=pd.to_datetime(LIBOR_USD.Date,dayfirst=True)
# LIBOR_USD.set_index('Date',inplace=True)
# LIBOR_USD.sort_index(inplace=True) 
# LIBOR_USD.to_excel("LIBOR.xlsx")
# LIBOR_USD.tail(2)

In [54]:
LIBOR=pd.read_excel('LIBOR.xlsx')
LIBOR.set_index('Date',inplace=True)
LIBOR.tail(2)

            LIBOR_3M
Date
2019-06-12   2.42788
2019-06-13   2.43000

In [ ]:
# Brent=pd.read_csv('BR.csv')
# Brent.drop(['<PER>', '<TIME>', '<OPEN>', '<HIGH>', '<LOW>', '<VOL>','<TICKER>'], 1, inplace=True)
# Brent.rename(columns={'<DATE>':'Date','<CLOSE>':'Brent'}, inplace=True)
# Brent.Date=pd.to_datetime(Brent.Date,format='%d/%m/%y')
# Brent.set_index('Date',inplace=True)
# Brent.tail(2)

In [ ]:
# RGBITR_Old=pd.read_excel('RGBITR_Old.xlsx')
# RGBITR_Old.drop(['BOARDID', 'SECID', 'SHORTNAME', 'NAME', 'OPEN', 'LOW', 'HIGH','DECIMALS', 'CURRENCYID',  'DIVISOR','VALUE','DURATION','CAPITALIZATION'], 1, inplace=True)
# RGBITR_Old.TRADEDATE=pd.to_datetime(RGBITR_Old.TRADEDATE)
# RGBITR_Old.rename(columns={'YIELD':'RGBITR_YIELD','CLOSE':'RGBITR','TRADEDATE':'Date'}, inplace=True)
# RGBITR_Old.set_index('Date',inplace=True)
# RGBITR_Old.tail(2)

In [22]:
# MOSPRIME=pd.read_excel('MOSPRIME.xlsx')
# # MOSPRIME=MOSPRIME.loc[MOSPRIME.name=='6M']
# # MOSPRIME.drop(['title', 'name'], 1, inplace=True)
# MOSPRIME.rename(columns={'Дата ставки': 'Date','2M': 'MOSPRIME_2M','3M': 'MOSPRIME_3M'},inplace=True)
# MOSPRIME['Date']=pd.to_datetime(MOSPRIME.Date,dayfirst=True)
# # MOSPRIME['MOSPRIME_6M']=MOSPRIME.MOSPRIME_6M.astype(float)
# # # LIBOR_USD.set_index('Date',inplace=True)
# MOSPRIME.head()

In [33]:
# STRATE_1W=pd.read_excel('STRATE_1W.xlsx')
# STRATE_1W.rename(columns={'tradedate': 'Date', 'rate':'STRATE_1W'},inplace=True)
# STRATE_1W.drop(['id'],1,inplace=True)
# STRATE_1W['Date']=pd.to_datetime(STRATE_1W.Date)
# STRATE_1W.set_index('Date',inplace=True)
# STRATE_1W.head(3)

In [34]:
# df=pd.merge(df,STRATE_1W,on='Date')
# df.head(3)

In [35]:
# STRATE_3M=pd.read_excel('STRATE_3M.xlsx')
# STRATE_3M.rename(columns={'tradedate': 'Date', 'rate':'STRATE_3M'},inplace=True)
# STRATE_3M.drop(['id'],1,inplace=True)
# STRATE_3M['Date']=pd.to_datetime(STRATE_3M.Date)
# STRATE_3M.set_index('Date',inplace=True)
# STRATE_3M.head(3)

In [36]:
# df=pd.merge(df,STRATE_3M,on='Date')
# df.head(3)

In [37]:
# STRATE_1Y=pd.read_excel('STRATE_1Y.xlsx')
# STRATE_1Y.rename(columns={'tradedate': 'Date', 'rate':'STRATE_1Y'},inplace=True)
# STRATE_1Y.drop(['id'],1,inplace=True)
# STRATE_1Y['Date']=pd.to_datetime(STRATE_1Y.Date)
# STRATE_1Y.set_index('Date',inplace=True)
# STRATE_1Y.head(3)

In [23]:
# RUSFAR = web.get_data_moex('RUSFAR', start, end)
# # USD_RUB=USD_RUB.loc[USD_RUB.BOARDID=='CETS']
# RUSFAR.drop(['BOARDID', 'SECID', 'SHORTNAME','NAME', 'VALUE', 'OPEN', 'LOW', 'HIGH', 'DURATION',  'YIELD','DECIMALS','CAPITALIZATION',
# 'CURRENCYID','DIVISOR'], 1, inplace=True)
# RUSFAR['Date']=RUSFAR.index
# RUSFAR['Date']=pd.to_datetime(RUSFAR.Date)
# RUSFAR.rename(columns={'CLOSE':'RUSFAR'}, inplace=True)
# RUSFAR.tail(2)

In [24]:
# df=pd.merge(RUSFAR,USD_RUB,on='Date')
# df.set_index('Date',inplace=True)
# # df.sort_index(inplace=True) 
# df

In [25]:
# df=pd.merge(df,USD_Repo,on='Date')
# # df.set_index('Date',inplace=True)
# # df.sort_index(inplace=True) 
# df.head()

In [27]:
# df=pd.merge(df,MOSPRIME,on='Date')
# df.head()

In [28]:
# NFEASWAP=pd.read_excel('NFEASWAP.xlsx')
# NFEASWAP.drop(['1W', '2W','1M', '2M','3M','6M','9M','18M','2Y','3Y','4Y','5Y'], 1, inplace=True)
# NFEASWAP.rename(columns={'1Y': 'NFEASWAP_1Y','Дата ставки': 'Date'},inplace=True)
# NFEASWAP['Date']=pd.to_datetime(NFEASWAP.Date,dayfirst=True)
# NFEASWAP['NFEASWAP_1Y']=NFEASWAP['NFEASWAP_1Y'].astype(float)
# # # LIBOR_USD.set_index('Date',inplace=True)
# NFEASWAP.head()

In [29]:
# df=pd.merge(df,Swap_12M,on='Date')
# df.head()

In [30]:
# df.dropna(inplace=True)
# df.corr()